wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-06
architecture:
  desc: null
  value: Transformer
dataset:
  desc: null
  value: UCF Crime
epochs:
  desc: null
  value: 15
train_batch_size:
  desc: null
  value: 1
validation_batch_size:
  desc: null
  value: 1
encoder_layers:
  desc: null
  value: 1
seed:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681127163.009887
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.14.2
      8:
      - 5
